export const amenititesData = [
    { name: "Paid parking" },
    { name: "Kitchen" },
    { name: "Pool" },
    { name: "Free parking" },
    { name: "Buthub" },
    { name: "TV" },
    { name: "Washer" },
    { name: "Campfire" },
    { name: "Outdoor dining area" },
    { name: "Air conditioning" },
    { name: "Exercise equipment" },
    { name: "Grill" },
    { name: "Outdoor Shower" },
    { name: "Wifi" },
    { name: "Dedicated workspace" },
    { name: "Carbon monoxide alerm" },
    { name: "Piano" },
    { name: "Ski in/ Ski out" },
    { name: "Safety alerm" },
    { name: "Tennis court" },
    { name: "First aid kit" },
]